<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TqkLibrary.VpnClient.Drivers.Fou\TqkLibrary.VpnClient.Drivers.Fou.csproj" />
    <ProjectReference Include="..\..\src\TqkLibrary.VpnClient.IpEncap\TqkLibrary.VpnClient.IpEncap.csproj" />
  </ItemGroup>

</Project>
